packages:
  - auth
  - e2e
  - export
  - export-and-sign
  - import
  - oauth-origin
  - oauth-redirect
  - shared
overrides:
  "minimatch@<3.1.3": "^3.1.4"
  "serialize-javascript@<7.0.2": "^7.0.3"
  "ws@<8.21.0": "^8.21.0"
allowBuilds:
  '@swc/core': false
  bufferutil: false
  unrs-resolver: false
  utf-8-validate: false
minimumReleaseAgeExclude:
  - '@turnkey/api-key-stamper@0.6.8'
  - '@turnkey/crypto@2.10.1'
  - '@turnkey/http@5.0.0'
  - '@turnkey/indexed-db-stamper@1.3.2'
  - '@turnkey/sdk-browser@7.0.0'
  - '@turnkey/sdk-types@1.2.0'
  - '@turnkey/wallet-stamper@1.1.20'
  - '@turnkey/sdk-server@7.0.0'
