apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: tkhq-auth-components
resources:
  - ../base
  - pdb.yaml
replicas:
  - name: auth-components
    count: 2
