apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: tkhq-auth-components
resources:
  - resources.yaml
images:
  - name: ghcr.io/tkhq/auth-components
