apiVersion: v1
kind: ServiceAccount
metadata:
  name: frames
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frames
spec:
  template:
    spec:
      initContainers:
        - name: template-quorum-key
          image: ghcr.io/tkhq/frames
          env:
            - name: TURNKEY_SIGNER_ENVIRONMENT
              value: "prod"
          command:
            - sh
            - -c
            - |
                mkdir -p templated/export templated/import templated/export-and-sign;
                
                envsubst '${TURNKEY_SIGNER_ENVIRONMENT}' < export/index.template.html > templated/export/index.html;

                # For export-and-sign, copy the webpack-built files and template the environment variable in JS files
                if [ -d "export-and-sign" ]; then
                  cp -r export-and-sign/. templated/export-and-sign/;
                  ls -la templated/export-and-sign/
                fi

                # Template the environment variable in the built JavaScript files
                for file in templated/export-and-sign/*.js; do
                  if [ -f "$file" ]; then
                    if sed "s/__TURNKEY_SIGNER_ENVIRONMENT__/${TURNKEY_SIGNER_ENVIRONMENT}/g" "$file" > "$file.tmp"; then
                      mv "$file.tmp" "$file"
                    fi
                  fi
                done

                # Do the same for import: copy the webpack-built files and template the environment variable in JS files
                if [ -d "/usr/share/nginx/import" ]; then
                  cp -r /usr/share/nginx/import/. templated/import/;
                  ls -la templated/import/
                fi

                # Template the environment variable in the built JavaScript files
                for file in templated/import/*.js; do
                  if [ -f "$file" ]; then
                    if sed "s/__TURNKEY_SIGNER_ENVIRONMENT__/${TURNKEY_SIGNER_ENVIRONMENT}/g" "$file" > "$file.tmp"; then
                      mv "$file.tmp" "$file"
                    fi
                  fi
                done
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - name: templated
              mountPath: /usr/share/nginx/templated
      containers:
        - name: frames
          image: ghcr.io/tkhq/frames
          ports:
            # iframes
            - name: auth
              containerPort: 8080
            - name: export
              containerPort: 8081
            - name: recovery
              containerPort: 8082
            - name: import
              containerPort: 8083
            - name: export-and-sign
              containerPort: 8086
            
            # oauth
            - name: oauth-origin
              containerPort: 8084
            - name: oauth-redirect
              containerPort: 8085
          livenessProbe:
            httpGet:
              path: /health
              port: auth
          resources:
            requests:
              memory: 5Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - name: templated
              mountPath: /usr/share/nginx/templated
              readOnly: true
      serviceAccountName: frames
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels: {}
          matchLabelKeys:
            - pod-template-hash
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels: {}
          matchLabelKeys:
            - pod-template-hash
      volumes:
        - name: templated
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: frames
spec:
  ports:
    # iframe
    - name: http-auth
      port: 8080
      targetPort: auth
    - name: http-export
      port: 8081
      targetPort: export
    - name: http-recovery
      port: 8082
      targetPort: recovery
    - name: http-import
      port: 8083
      targetPort: import
    - name: http-exp-sign
      port: 8086
      targetPort: export-and-sign
    
    # oauth
    - name: http-oauth-og
      port: 8084
      targetPort: oauth-origin
    - name: http-oauth-rd
      port: 8085
      targetPort: oauth-redirect
