name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: # Allows manual invocation

jobs:
  build:
    name: Build
    uses: ./.github/workflows/reusable-build.yml

  tests:
    name: Test
    needs: build
    uses: ./.github/workflows/reusable-test.yml
